version: '2.2'
services:

  grafana:
    image: grafana/grafana
    volumes:
      - /home/admin/docker/grafana/lib:/var/lib/grafana
      - /home/admin/docker/grafana/conf:/etc/grafana
      - /home/admin/docker/grafana/log:/var/log/grafana
    expose:
      - '3000'

  prometheus:
    image: prom/prometheus:master
    volumes:
      - /home/admin/docker/prometheus/conf:/etc/prometheus/
      - /home/admin/docker/prometheus/data:/prometheus
    expose:
      - '9090'

  node-exporter:
    image: prom/node-exporter
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    expose:
      - '9100'
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points="^/(sys|proc|dev|host|etc)($$|/)"'

  cadvisor:
    image: google/cadvisor
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run
      - /sys:/sys:ro
      - /var/lib/docker:/var/lib/docker:ro
    expose:
      - '8080'
