version: '2.2'
services:

  heinz:
    image: registry.net-sec.ch/net-sec/elasticsearch-kibana:kibana4
    volumes:
      - /home/admin/docker/elasticsearch-heinz/elasticsearch:/home/elasticsearch/elasticsearch/data
    expose:
      - '9200'
      - '5601'
    environment:
      - KIBANA_BASE_PATH="/heinz/kibana"
